### ISSUE TITLE
Referências com mais de três autores estão sendo 'abreviadas' com et al. na lista de referências

### ISSUE THREAD

**Issue by brunopick** [eduardoweiland/latex-unisc#11]
Exemplo de referência que está sendo abreviada.

@article{Sorgato:2014,
   title = {{Análise do procedimento de simulação da NBR 15575 para avaliação do desempenho térmico de edificações residenciais}},
   journal = {{Ambiente Construído}},
   author={Sorgato, Marcio José AND Melo, Ana Paula AND Marinoski, Deivis Luís AND Lamberts, Roberto},
   ISSN = {1678-8621},
   URL = {http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1678-86212014000400007&nrm=iso},
   volume = {14},
   number = {4},
   year = {2014},
   month = {12},
   pages = {83 - 101},
   publisher = {scielo},
}

**Comment by eduardoweiland** [comment]
Isso está correto pelas normas da UNISC: http://www.unisc.br/editora/e_books_normas.pdf
