### ISSUE TITLE
Problemas de internacionalização.

### ISSUE THREAD

**Issue by flepsxd** [eduardoweiland/latex-unisc#12]
Ao tentar compilar o projeto recebo os erros:

```
/usr/local/texlive/2016/texmf-dist/tex/generic/babel-portuges/portuges.ldf, line 50
Missing number, treated as zero.
<to be read again> 
                   \l@brazilian 
l.50 ...Init\CurrentOption{captions\CurrentOption}
                                                  
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)

==========================================
Package babel Error: You haven't defined the language brazilian yet.
See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.28 \select@language{brazilian}
                                
Your command will be ignored, type <return> to proceed
```

**Comment by eduardoweiland** [comment]
@flepsxd Você poderia adicionar aqui no issue o preâmbulo do seu arquivo principal? Desde o `\documentclass` até o `\begin{document}`. Seria bom também se você pudesse informar qual editor está utilizando e, se estiver compilando os arquivos manualmente, quais comandos está utilizando.

Eu acho que o problema pode ser apenas algum `\usepackage` faltando, ou alguma configuração do ambiente. Eu tentei compilar o projeto de exemplo aqui com o texlive-2016-32.20160520 no Fedora 25 e não tive nenhum erro.

**Comment by flepsxd** [comment]
Olá @eduardoweiland ,

Estou utilizando o ShareLatex em meu projeto. Ano passado consegui compilar porém ao abrir esse ano não está mais funcionando corretamente. Abaixo seguem dados solicitados.

\documentclass[tc]{unisc} 

\usepackage[T1]{fontenc}        % Suporte a acentuação no arquivo de saída
\usepackage[utf8]{inputenc}     % Codificação dos arquivos de entrada em UTF-8
\usepackage[english,brazilian]{babel}

\usepackage{graphicx}           % Para adicionar figuras
\usepackage{float}              % Maior controle de objetos "float" (tabelas, figuras, etc.)

\usepackage{capt-of}
\usepackage{longtable}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{tabularx}


\graphicspath{ {images/} }


% ==================================================================================
%
%                         INFORMAÇÕES GERAIS
%
% ==================================================================================

\title{IMPLEMENTAÇÃO DE UM SISTEMA DE DETECÇÃO DE INTRUSÃO DE REDE UTILIZANDO ARQUITETURA RECONFIGURÁVEL}

\author{Helfer}{Felipe André}
\advisor[Prof. Msc.]{Neu}{Charles}
\reviewer[Prof. Me.]{Assmann}{Daniel}
\reviewer[Prof. Me.]{Muller}{Lucas Fernando}

\dept{Departamento de Computação}
\course{Curso de Engenharia de Computação}
\degree{Bacharel em Engenharia de Computação}
\location{Santa Cruz do Sul}{RS}
\date{23}{junho}{2017}

\makeindex

% ==================================================================================
%
%                         CONTEÚDO
%
% ==================================================================================


\begin{document}


============Erros========================
 /usr/local/texlive/2016/texmf-dist/tex/generic/babel-portuges/portuges.ldf, line 50
Missing number, treated as zero.
<to be read again> 
                   \l@brazilian 
l.50 ...Init\CurrentOption{captions\CurrentOption}
                                                  
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
==============
Package babel Error: You haven't defined the language brazilian yet.
See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.28 \select@language{brazilian}
                                
Your command will be ignored, type <return> to proceed
====================

**Comment by eduardoweiland** [comment]
Consegui reproduzir o erro em um projeto novo no ShareLaTeX. Estranho é que os projetos antigos continuam funcionando. O ShareLaTeX deve ter atualizado o ambiente de compilação dos projetos novos e os antigos continuam como estavam antes.

Vou continuar testando e procurando a causa do erro. Enquanto isso, se você tiver um projeto antigo no ShareLaTeX, pode copiar o conteúdo novo para ele que deve funcionar.

**Comment by eduardoweiland** [comment]
@flepsxd Fiz uma [correção na classe unisc.cls](https://github.com/eduardoweiland/latex-unisc/commit/f39afbd1ae13d24cf128f2fdecde21a0a09b250d), você pode tentar compilar novamente com essa modificação para ter certeza de que está funcionando?

**Comment by flepsxd** [comment]
@eduardoweiland , agora funcionou de forma correta. Muito obrigado pela correção e sua atenção.
