### ISSUE TITLE
Lista de Abreviaturas não é gerada no ShareLaTeX

### ISSUE THREAD

**Issue by leandrohaupt** [eduardoweiland/latex-unisc#13]
Utilizando o exemplo de TC disponibilizado o comando

> \input{pre_textual/05.abreviaturas.tex}

não esta gerando a lista de abreviaturas no documento.

**Comment by eduardoweiland** [comment]
@leandrohaupt Você já tentou remover os arquivos em cache e compilar novamente? Eu lembro que [isso era necessário](https://github.com/eduardoweiland/latex-unisc#compila%C3%A7%C3%A3o-com-o-modelo) após alterar as abreviaturas utilizadas...

**Comment by leandrohaupt** [comment]
@eduardoweiland sim tentei fazer isso

tornei o projeto público se quiser dar uma olhada
https://pt.sharelatex.com/project/58e570190a678a956d3f1e29

**Comment by eduardoweiland** [comment]
Ah, provavelmente o problema é que o arquivo principal não está na raiz do projeto. Nunca testei dessa forma, sempre utilizei o arquivo .tex principal no mesmo nível dos arquivos da classe (unisc.cls e outros).

Criei um projeto do zero agora e coloquei o código de exemplo do repositório, na estrutura que eu sempre utilizei, e a lista de abreviaturas foi gerada normalmente. Pode ver nesse projeto como devem ficar os arquivos: https://pt.sharelatex.com/project/58e5729a0a678a956d3f1f1a

**Comment by leandrohaupt** [comment]
@eduardoweiland era exatamente isso, obrigado pela solução e atenção

**Comment by eduardoweiland** [comment]
@leandrohaupt Que bom que você conseguiu resolver o problema 😄

Vou adicionar um aviso na página do projeto informando sobre essa restrição na estrutura de arquivos para evitar que mais pessoas tenham esse problema.
