### ISSUE TITLE
Atualização das normas para 2017 - Sumário

### ISSUE THREAD

**Issue by clarel** [eduardoweiland/latex-unisc#14]
Este ano saiu uma nova versão das normas, disponível no virtual

Normas para apresentação de trabalhos acadêmicos
2ª edição
Inácio Helfer
Helga Haas
Clarice Agnes
2017

Até agora, olhando por cima, constatei que o espaçamento no SUMÁRIO após um capítulo foi modificado.
![sem titulo](https://cloud.githubusercontent.com/assets/9810048/26028562/d362c508-37f9-11e7-8007-c31136eccef3.png)

**Comment by eduardoweiland** [comment]
Fiz uma comparação entre a [edição antiga das normas](http://www.unisc.br/editora/e_books_normas.pdf) e a [nova edição](http://unisc.br/images/upload/com_editora_livro/EbookNormas2017.pdf). Pelos exemplos incluídos nos apêndices do livros de normas, parece que a única modificação é o espaçamento no sumário, mas as duas edições indicam o uso da norma ABNT NBR 6027, de 2012. Olhando o ABNTeX, que também usa a NBR 6027, parece que o correto mesmo é com esse espaçamento.
