### ISSUE TITLE
Não permite adicionar mais de 1 co-orientador

### ISSUE THREAD

**Issue by rutsatz** [eduardoweiland/latex-unisc#15]
Estou adicionando dois co-orientados com o comando abaixo:

Estou usando o modelo de proposta
`\documentclass[propostatc]{unisc} `

e o comando:

`\coadvisorF[Profa. Dra.]{Sobrenome1}{Nome1}`
`\coadvisor[Prof. Dr.]{Sobrenome2}{Nome2}`

Porém, ao compilar, aparece somente o segundo co-orientador.

**Comment by eduardoweiland** [comment]
Realmente não tem essa possibilidade no modelo. O problema é que o livro de normas da UNISC não possui nenhuma informação sobre como exibir os nomes quando houver mais de um coorientador, e até o [abnTeX](https://github.com/abntex/abntex2) não tem suporte a isso.

Eu não tenho as normas da ABNT para saber como isso deve ser apresentado, mas se o abnTeX não fez provavelmente também não tem nada disso nas normas da ABNT.

Você poderia perguntar para o seu orientador como isso deve ser exibido? Incluindo espaçamento, alinhamento, locais para exibir etc.

**Comment by rutsatz** [comment]
No caso, o terceiro integrante vai entrar como especialista humano, então não vai precisar adicionar outro co-orientador.

**Comment by rutsatz** [comment]
Olá!

Então, estou novamente com esse assunto pois conversei com o orientador e para o TC vou precisar adicionar dois co-orientadores. 

Por isso queria ver se é possível, para o TC, adicionar mais um co-orientador?

Pode ser usado o estilo que tem hoje, adicionando mais um co-orientador abaixo do co-orientador que já existe.

Abaixo tem a imagem de como está hoje:
![screenshot from 2018-05-15 23-28-35](https://user-images.githubusercontent.com/14064725/40093282-ce04db40-5897-11e8-8955-cd405df39fdc.png)

Aí abaixo do co-orientador, adicionaríamos mais uma linha.

Abraços e obrigado!

**Comment by rutsatz** [comment]
Obrigado pelo retorno @eduardoweiland 

Eu fiz a primeira opção, editando somente as alterações, e funcionou perfeitamente!

Obrigado!

Abraços!
