### ISSUE TITLE
Ajuste na folha de rosto e nas referências

### ISSUE THREAD

**Issue by rutsatz** [eduardoweiland/latex-unisc#16]
Estou usando o ShareLatex para minha proposta de TC e tem algumas correções que a professora fez.

Estou usando o modelo de proposta disponibilizado na wiki.

Na folha de rosto, está sendo adicionado entre parênteses "Título Provisório" e deveria ser removido. 
Eu estou usando: `\title{Software para estimular a cognição de pacientes diagnosticados com a Doença de Alzheimer}` e ele está gerando:

![screenshot from 2017-12-05 21-20-02](https://user-images.githubusercontent.com/14064725/33636136-20aa830a-da02-11e7-84a6-845bb8d1eab2.png)

E a data deve ser somente o ano, abaixo da cidade. Eu estou usando: 
```
\location{Santa Cruz do Sul}{RS}
\date{2017}
```
e ele está gerando:

![screenshot from 2017-12-05 21-21-52](https://user-images.githubusercontent.com/14064725/33636203-5e9f0a78-da02-11e7-9946-9d47399598dd.png)

Na parte das referências, também existem dois pontos que a professora pediu para corrigir.
Nas referências, quando existe mais de um autor, não deve aparecer _et al._, mas sim citar todos os autores (o _et al._ deve aparecer somente no texto). 
Eu estou usando:

```
@article{Relato_de_caso_Treino_de_memoria,
   title = {{Memory training and benefits for quality of life in the elderly: A case report}},
   journal = {{Dementia \& Neuropsychologia}},
   author={Assed, Mariana Medeiros AND Carvalho, Martha Kortas Hajjar Veiga de AND Rocca, Cristiana Castanho de Almeida AND Serafim, Antonio de P\~A!`dua},
   language = {en},
   URL = {http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1980-57642016000200152&nrm=iso},
   volume = {10},
   year = {2016},
   month = {06},
   pages = {152 - 155},
   publisher = {scielo},
   DOI = "http://dx.doi.org/10.1590/S1980-5764-2016DN1002012"
}

```
e ele está gerando:

![screenshot from 2017-12-05 21-27-46](https://user-images.githubusercontent.com/14064725/33636427-3098a552-da03-11e7-9ad3-d4609a4cde85.png)

(Não deveria ter o _et al._, mas listar todos os autores).

E o segundo item, eu estou usando:

```
@misc{InstitutoAlzheimerBrasil,
	author = {Instituto Alzheimer Brasil},
	url = {http://www.institutoalzheimerbrasil.org.br},
	howpublished = {http://www.institutoalzheimerbrasil.org.br},
	year = {2017},
	note = {Acesso em: 26 de novembro de 2017.}
}
```

e ele está gerando:

![screenshot from 2017-12-05 21-31-12](https://user-images.githubusercontent.com/14064725/33636509-a76bd154-da03-11e7-8cd9-08abbf439350.png)

porém o **Acesso em:** deveria aparecer por último, após o **Disponível em:**.

**Comment by eduardoweiland** [comment]
Olá Rafael.

## Sobre a folha de rosto

Resumindo: Não existe um padrão.

Quando eu fiz a minha proposta, eu peguei vários exemplos de outros colegas e fiz como está nos exemplos porque foi o modelo com "maioria de votos" (era o mais usado). Mas vários outros modelos muito diferentes também eram aceitos, então eu não sei se eu vou adicionar essas alterações no projeto principal.

O que eu posso fazer é te ajudar a alterar e personalizar o modelo, removendo o "título provisório" e deixando apenas o ano na data. Acho que amanhã eu consigo um tempo para ver isso, aí eu vou postar um comentário aqui com os ajustes necessários.

## Sobre as referências

Sobre isso, eu preciso citar o [manual do abntex2cite](http://repositorios.cpai.unb.br/ctan/macros/latex/contrib/abntex2/doc/abntex2cite.pdf), que é o pacote utilizado para formatar as referências:

> Cuidado: normas nebulosas!
>
> Nós elaboramos os estilos debruçados diretamente sobre os originais da ABNT e as seguimos escrupulosamente. Mas não se iluda! O que a sua coordenação de pós-graduação, ou orientador, ou chefe etc., entendem por ‘normas ABNT’ pode não ter qualquer vínculo com a realidade

Dito isso, vendo agora os problemas mais específicos:

### Acesso em

O manual do abntex2cite que eu linkei acima tem alguns exemplos, incluindo um que tem "Disponível em" e "Acesso em" (p. 28-29). Aparentemente, em vez de colocar a data de acesso em `note`, você deveria colocar `urlaccessdate={26 de novembro de 2017}`. **Eu não testei isso**, mas provavelmente deve funcionar.

### _et al_

Aqui eu vou precisar discordar da sua orientadora. Isso já foi reportado antes (#11) e não será ajustado, por 2 motivos:

1) Colocar o "et al" nesse caso é o "correto" segundo as normas da ABNT (_baseado em exemplos do abntex2cite_)
2) Colocar o "et al" nesse caso é o "correto" segundo as normas da UNISC (_baseado em exemplos das normas da UNISC_)

No [ebook de normas da UNISC](http://www.unisc.br/editora/e_books_normas.pdf), seção 6.1.1:

![screenshot-20171205220417-513x182](https://user-images.githubusercontent.com/1799015/33637470-4b120004-da08-11e7-9f2e-7a58cccc4c32.png)

**Comment by rutsatz** [comment]
Eduardo, obrigado pelo retorno.

Se você puder verificar como fazer a personalização da folha de rosto, vou ajustar no meu modelo daí.

Sobre as referências, testei a sua sugestão: `urlaccessdate={26 de novembro de 2017}` e funcionou. Muito obrigado.

**Comment by rutsatz** [comment]
Sobre o **et al.**, a professora falou que é assim que é utilizado externamente em todos os lugares, por isso é feito assim com os trabalhos.

Você sabe como alterar isso?

Obrigado!

**Comment by eduardoweiland** [comment]
Rafael, os ajustes que você precisa fazer na folha de rosto para remover o "Título Provisório" e deixar apenas o ano no lugar da data completo são bem simples.

Você vai precisar editar o arquivo **propostatc.def**. O ShareLaTeX não suporta esse formato de arquivo, então você vai precisar baixar ele e abrir em um editor de texto (um gedit no Linux ou um Notepad++ no Windows, por exemplo).

Para ajustar a data, você precisa encontrar essas linhas no arquivo

```tex
\newcommand{\titlepagedate}{%
  \centerline{\@city, \unisc@date}
}
```

E trocar por essas:

```tex
\newcommand{\titlepagedate}{%
  \centerline{\@city}
  \centerline{\@publyear}
}
```

Mas você ainda vai precisar usar o comando `\date` com todos os parâmetros do template, mesmo que vazios:

```tex
\date{}{}{2017}
```

Isso resolve a data. Agora, para remover o "Título Provisório", ainda no mesmo arquivo e logo abaixo dessas linhas alteradas deve ter um código assim:

```tex
\newcommand{\titlewinboxcontent}{%
  \vspace*{6cm}
  \vspace{\stretch{3}}
  {\textbf{\MakeUppercase{\@title}}\par}
  \temppropname\\
  \vspace*{1cm}
  \byname\\
  \vspace*{1cm}
  \@authora\\
  \@ifundefined{@authorb}{}{\@authorb\\}%
  \@ifundefined{@authorc}{}{\@authorc\\}%
  \@ifundefined{@authord}{}{\@authord\\}%
  \vspace*{1cm}
  \proptcspecificinfo\\
  \vspace*{1cm}
}
```

Você só precisa remover a linha `\temppropname\\` e deve resolver.

Depois de editar o arquivo você vai precisar enviá-lo novamente para o ShareLaTeX e sobrescrever o que já estava lá.

**Comment by eduardoweiland** [comment]
Rafael, sobre o _et al_, eu estava lendo agora no manual do abntex2cite e encontrei uma solução, bem simples também.

No arquivo principal do trabalho, logo depois do `\begin{document}`, coloque a seguinte linha:

```tex
\citeoption{abnt-etal-list=0}
```

Isso vai desabilitar o uso do _et al_ nas referências.

**Comment by rutsatz** [comment]
Eduardo,

muito obrigado pela sua atenção. Consegui fazer todos os ajustes seguindo suas dicas. 

**Valeu!**

Eu também removi os avaliadores na folha de rosto. Vou deixar abaixo o que fiz, caso mais alguém precise:

No arquivo **propostatc.def**, alterei a linha:

`\reviewersname\\\vspace*{3cm}`

por 

`\vspace*{3cm}`

**Comment by eduardoweiland** [comment]
Ótimo, bom saber que foi tudo resolvido!

Eu vou fechar este issue então, mas qualquer coisa pode abrir um novo.
