### ISSUE TITLE
Lista de Quadros

### ISSUE THREAD

**Issue by rutsatz** [eduardoweiland/latex-unisc#17]
Olá!

To aqui incomodando novamente! Hehehe! Mas o orientador pediu mais uma coisa. Ele pediu pra separar a lista de tabelas e a lista de quadros. Pelo que pesquisei, no abnt tu precisa separar as tabelas e os quadros. Tabelas para números e quadros para textos. Então, eu precisaria adicionar essa lista de quadros.

Eu tentei fazer sozinho, mas os exemplos que encontrei na internet sempre dão algum erro.

Eu to usando o ShareLatex, e criei um projeto de exemplo pra compartilhar, em que ocorre o problema:

https://www.sharelatex.com/3226666735zzxgzmmjypck

Esse é um projeto só de teste, então pode editar, se precisar.

Essa é uma imagem do erro:
![capture](https://user-images.githubusercontent.com/14064725/41016834-5063dc8a-6928-11e8-9436-deb5a82ccac5.PNG)

Esse código do exemplo, eu retirei desse link:
https://www.facebook.com/Latexusers/posts/977693342306154

Eu percebi que o erro acontece depois que eu adiciono o \caption dentro do \begin{quadro} \end{quadro}. 
Assim não dá erro:
`\begin{quadro}
Isso é um quadro
\end{quadro}`

Adicionando o caption, aparece o erro:
`\begin{quadro}
Isso é um quadro
\caption{Quadro comparativo}
\label{qua:quadro_comparativo}
\end{quadro}`

Como dentro do quadro eu vou colocar uma tabela, então eu vou precisar do \caption em cima da tabela e do \fonte na parte de baixo.

Desde já obrigado!

Abraços!

**Comment by eduardoweiland** [comment]
Para criar as listagens é utilizado o pacote [glossaries](http://mirrors.ctan.org/macros/latex/contrib/glossaries/glossaries-user.pdf). Precisa dar uma olhada na documentação para saber como criar um novo tipo de itens.

**Comment by eduardoweiland** [comment]
Fechando por não ter mais respostas no tópico. Se necessário, o issue pode ser aberto novamente.

**Comment by rutsatz** [comment]
Para quem quiser adicionar a lista de quadros:

Edite o arquivo **unisc.cls** e adicione a linha abaixo:
`\settocfeature[lop][1]{entryhook}{\quadroname~\hskip\leftskip}`
abaixo da linha:
`\settocfeature[lot][1]{entryhook}{\tablename~\hskip\leftskip}`

Edite o arquivo **namedefs.babel** e adicione a linha abaixo:
`\def\listquadroname{Lista de Quadros}%`
abaixo da linha:
`\def\listtablename{Lista de Tabelas}%`

No arquivo .tex, adicione o código abaixo no prêambulo do arquivo:
```
\usepackage{float}
\floatstyle{plaintop} % Coloca caption no topo
\newfloat{quadro}{htbp}{lop}
\floatname{quadro}{Quadro}
\newcommand{\listofquadros}{\listof{quadro}{Lista de Quadros}}
\captionsetup[quadro]{listformat=simple}
```

Para gerar a lista de quadros, use o comando:
`\listofquadros`

Para usar o quadro, use o comando:
```
\begin{quadro}
\end{quadro}
```

Exemplo de uso:
```
\begin{quadro}[!ht]
\centering
\caption{Quadro tal e tal.}
\label{quadro:quadro_x}
\begin{tabular}{cc}
123 & 456\\
123 & 456\\
\end{tabular}
\fonte{Os autor}
\end{quadro}
```

**Comment by lsbrito** [comment]
Resolveu mas agora quero que apareça conforme a formatação abaixo:
Tabela 1 – TABELA tal e tal. . .

**Comment by eduardoweiland** [comment]
@lsbrito Eu não sei se entendi exatamente qual é o formato que você está tentando utilizar, mas se é apenas colocar o travessão depois do número da figura/tabela, você pode editar o arquivo _unisc.cls_, na seção "Redefinição do conteúdo das listas de figuras e tabelas" com a seguinte alteração:

```diff
   \if@captionlisting%
     \addcontentsline{\csname ext@#1\endcsname}{#1}%
-        {\protect\numberline{\csname fnumx@#1\endcsname}{\ignorespaces #2}}%
+        {\protect\numberline{\csname fnumx@#1\endcsname~--}{\ignorespaces #2}}%
   \fi%
```

Isso vai alterar o formato na lista de figuras e na lista de tabelas, mas não na lista de códigos (se você estiver utilizando).
