### ISSUE TITLE
Formatação da Lista de Abreviaturas e et. al

### ISSUE THREAD

**Issue by rutsatz** [eduardoweiland/latex-unisc#18]
Tem mais duas alterações que foram solicitadas.

Na Lista de Abreviaturas, a quebra de linha está ocorrendo no meio da página. Exemplo:
![lista_abreviatuas](https://user-images.githubusercontent.com/14064725/41825162-67f6dbb2-77f2-11e8-8a03-c565951ecf03.PNG)

No exemplo acima, a pavra Alzheimer não deveria estar quebrando a linha.

E o outro detalhe é relacionado com as citações. Quando tem mais de três autores e o sistema coloca o et al, ele deve estar em itálico. Exemplo:

![italico](https://user-images.githubusercontent.com/14064725/41825193-ce783110-77f2-11e8-9d23-b402a73567ef.PNG)

No exemplo acima, foi feita a citação através do \cite{} e o et al deveria aparecer em itálico.

Abaixo segue um projeto de exemplo:
https://www.sharelatex.com/9671799293vskddrsfcsnt

Obrigado!

**Comment by eduardoweiland** [comment]
1. a largura da coluna da descrição não é calculada automaticamente, é necessário alterar com `\setlength{\glsdescwidth}{14cm}` (antes dos `\newacronym`)
2. et al. não deve ser itálico mesmo, está nas normas.

**Comment by eduardoweiland** [comment]
Como está documentado no README, as referências são criadas com o pacote abnTeX, então para alterar o et al. é necessário ver a [documentação dele](http://repositorios.cpai.unb.br/ctan/macros/latex/contrib/abntex2/doc/abntex2cite.pdf). Mas basicamente é apenas editar o **unisc.cls** e trocar:

```tex
\RequirePackage[alf]{abntex2cite}  % Estilo de referências da ABNT
```

Por: 

```tex
\RequirePackage[alf,abnt-etal-text=emph]{abntex2cite}  % Estilo de referências da ABNT
```

Mas, só para deixar claro, fazendo isso o seu trabalho não estará de acordo com as normas da UNISC e sim com as normas dos professores que pediram a alteração.

**Comment by rutsatz** [comment]
Obrigado @eduardoweiland!

Funcionou corretamente!

Abraços!
