### ISSUE TITLE
Nova versão 3ª edição

### ISSUE THREAD

**Issue by willserafini** [eduardoweiland/latex-unisc#20]
https://repositorio.unisc.br/jspui/bitstream/11624/2509/1/Normas%20para%20apresenta%C3%A7%C3%A3o%20de%20trabalhos%20acad%C3%AAmicos%20-%203.ed.pdf

**Comment by eduardoweiland** [comment]
@willserafini Obrigado por informar sobre a terceira edição, eu não estava sabendo dela ainda.

De acordo com a introdução dessa nova edição, "as seções e subseções 2 a 5 apresentam apenas adequações resultantes de sugestões da comunidade acadêmica e da revisão atualizada do texto"¹.

Eu comparei a 2ª e a 3ª edição e, realmente, não existe nenhuma alteração na formatação do documento. "O destaque da edição está na seção 6, totalmente reformulada, diante da publicação da ABNT NBR 6023, 2. ed. 2018 que trata da informação e documentação dos elementos a serem incluídos nas referências dos diferentes tipos de documento."¹.

Embora o LaTeX UNISC não seja baseado no modelo do abnTeX2, para as referências é utilizado o pacote abntex2cite. Infelizmente, o abntex2cite [ainda não está 100% de acordo](https://github.com/abntex/abntex2/issues/210) com a nova norma, mas parece que [já existe algum progresso](https://github.com/abntex/biblatex-abnt/issues/42).

Acho que não existe nada que possa ser feito no momento no LaTeX UNISC. Mas você pode tentar instalar o [biblatex-abnt](https://github.com/abntex/biblatex-abnt) mais atualizado direto do repositório e utilizá-lo para as referências.

___
1) HELFER, I.; HAAS, H.; AGNES, C. _Normas para apresentação de trabalhos acadêmicos._ 3. ed. Santa Cruz do Sul, RS:  EDUNISC, 2019. ISBN 978-85-7578-503-4. Disponível em: https://www.unisc.br/pt/home/editora/e-books?id_livro=487.
