### ISSUE TITLE
Como escrever o "et. al" em formato itálico nas citações ?

### ISSUE THREAD

**Issue by dorisavaiot** [eduardoweiland/latex-unisc#21]
_###_ Ambiente

Overleaf

### Projeto de exemplo

Estou usando na dissertação e me questionaram pq. o "et. al" não está em _itálico_ já que também é uma expressão estrangeira? Entendo que por isso deveria estar em itálico também, mas não sei onde alterar esta configuração.

**Comment by eduardoweiland** [comment]
@dorisavaiot O "et al.", em todos os exemplos das normas da UNISC, **não está em itálico**. Acredito que o correto seja manter como está.

Mas se os orientadores estão pedindo para alterar para itálico, isso pode ser feito com uma opção. Já comentei como fazer isso [nesse issue](https://github.com/eduardoweiland/latex-unisc/issues/18#issuecomment-401182231). Vou editar o README para incluir essa informação.

**Comment by eduardoweiland** [comment]
Na verdade, agora que eu vi que o et al. está em itálico na 3ª edição das normas (não estava na 2ª edição). Então acho que o modelo padrão deve ser alterado sim. Mas a alteração é a mesma que eu comentei acima.

**Comment by eduardoweiland** [comment]
Corrigido na [versão 1.3.0](https://github.com/eduardoweiland/latex-unisc/releases/tag/v1.3.0).

**Comment by dorisavaiot** [comment]
Muito obrigado!
Ótimo trabalho como sempre!
