### ISSUE TITLE
Items de anexo no sumário estão se sobrepondo

### ISSUE THREAD

**Issue by brunopick** [eduardoweiland/latex-unisc#8]
Em um documento se for adicionado mais de um anexo estes ficam sobrepostos na lista do sumário.

Imagem de demonstração com 2 anexos:
![anexos](https://cloud.githubusercontent.com/assets/9522370/20033603/8a66769a-a38b-11e6-929c-0e4d35c27bb9.png)

**Comment by brunopick** [comment]
Com 7 anexos: 
![anexos](https://cloud.githubusercontent.com/assets/9522370/20033617/e31e448e-a38b-11e6-9157-6a5ae92d5ae2.png)

**Comment by eduardoweiland** [comment]
Projeto no ShareLaTeX para testar a correção dos anexos: https://pt.sharelatex.com/project/581e4be4a5714a4b454072db

Pode ser acompanhado o desenvolvimento nesse projeto.

**Comment by eduardoweiland** [comment]
Alguns exemplos de como deveria ficar a formatação correta:

**Itens de anexo no sumário**: sem numeração de capítulo, identificação de ANEXO A fica alinhado com os demais títulos, nenhum item indicando o início dos anexos.
![formatacao do anexo no sumario](https://cloud.githubusercontent.com/assets/1799015/20033727/d8f1700a-a38e-11e6-9463-32189383002d.png)

**Título na página do anexo**: centralizado, mesmo em caso de quebra de linha
![titulo no anexo](https://cloud.githubusercontent.com/assets/1799015/20033728/d94bcad2-a38e-11e6-9a15-a3eda2f7beb2.png)

![titulo no anexo com quebra de linha](https://cloud.githubusercontent.com/assets/1799015/20033742/710735f0-a38f-11e6-9e3d-bd3a5099456b.png)


Exemplos reproduzidos de: AGNES, C.; HELFER, I. Normas para apresentação de trabalhos acadêmicos. 1. ed. atual. Santa Cruz do Sul, RS: EDUNISC, 2013. ISBN 9788575782033.

**Comment by eduardoweiland** [comment]
@brunopick Pode testar com a versão mais recente no master para verificar se está melhor. Ainda tem um pequeno problema para ser corrigido (#10), mas do jeito que está pelo menos já é algo mais apresentável.

**Comment by brunopick** [comment]
Testei aqui e funcionou.

**Comment by brunopick** [comment]
Testei aqui e funcionou, obrigado pela correção.
