### ISSUE TITLE
Primeiro item de anexo no sumário não possui numeração de página

### ISSUE THREAD

**Issue by brunopick** [eduardoweiland/latex-unisc#9]
O primeiro item de anexo no sumário está sem númeração de página e no fim do titulo do anexo fica o texto "45chapter.1".

Com mais de um item no anexo não consegui ver se isso acontece ou não pois como está informado no issue #8 os items estão ficando sobrepostos.

![ane](https://cloud.githubusercontent.com/assets/9522370/20033656/dce162b2-a38c-11e6-8ece-cdb2cf411fae.png)

**Comment by eduardoweiland** [comment]
Tudo bugado nesses anexos pelo jeito... vou revisar toda essa parte então, talvez eu ache mais coisas pra corrigir.
